import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import { CollectionOptionPage } from "../Pages/CollectionOptionPage";
import { LabelsAndDocumentsPage } from "../Pages/LabelsAndDocumentsPage";
import { TrackingHistoryPage } from "../Pages/TrackingHistoryPage";
import { CommercialInvoicePage } from "../Pages/CommercialInvoicePage";
import exportData from "../Test-data/exportInternationalTestData.json";
//import exportData  from "../Test-data/exportVanuatu.json";
for(const exporTestData of exportData){
test.setTimeout(1200000)
test(`The test title ${exporTestData.testTitle}`, async ({page,context}) => {
    const login = new LoginPage(page,context)
    const exportPage = new ExportDomesticPage(page,context)
    const collectionPage = new CollectionOptionPage(page,context)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    const trackingHistory = new TrackingHistoryPage(page,context)
    const commercialInvoice = new CommercialInvoicePage(page,context)

    await login.loadingURL()
    await exportPage.clickingExportPage()
    await exportPage.exportPageSpinner()
    await page.waitForTimeout(6000)
    await exportPage.enteringCollectionCompanyName(exporTestData.collectionCompany)
    await exportPage.enteringCollectionContactName(exporTestData.collectionConctact)
    await exportPage.enteringCollectionAddress1(exporTestData.collectionAddress1)
    await exportPage.enteringCollectionCountry(exporTestData.collectionCountry)
    await exportPage.clickingCollectionState(exporTestData.collectionState,exporTestData.collectionCountry)
    await exportPage.enteringCollectionCity(exporTestData.collectionCity)
    await exportPage.enteringCollectionPostcode(exporTestData.collectionPostcode)
    await exportPage.enteringCollectionDial(exporTestData.collectionDial)
    await exportPage.enteringCollectionPhone(exporTestData.collectionPhone)
    await exportPage.enteringCollectionEmailID(exporTestData.collectionEmail)
    await exportPage.enteringDeliveryCompanyName(exporTestData.deliveryCompany)
    await exportPage.enteringDeliveryContactName(exporTestData.deliveryContact)
    await exportPage.enteringDeliveryAddress1(exporTestData.deliveryAddress1)
    await exportPage.clickingDeliveryCountry(exporTestData.deliveryCountry)
    await exportPage.clickingDeliveryState(exporTestData.deliveryState,exporTestData.deliveryCountry)
    await exportPage.enteringDeliveryCity(exporTestData.deliveryCity)
    await exportPage.enteringDeliveryPostcode(exporTestData.deliveryPostcode)
    await exportPage.enteringDeliveryDial(exporTestData.deliveryDial)
    await exportPage.enteringDeliveryPhone(exporTestData.deliveryPhone)
    await exportPage.enteringDeliveryEmailID(exporTestData.deliveryEmail)
    await exportPage.clickingResidential(exporTestData.residentialCollection,exporTestData.residentialDelivery)
    await exportPage.clickingPOBoxDelivery(exporTestData.poBoxDelivery)
    await exportPage.clickingServiceCompany(exporTestData.serviceCompany)
    await exportPage.clickingServiceType(exporTestData.serviceType)
    await exportPage.clickingPackageType(exporTestData.packageType)
    await exportPage.enteringCustomerRef(exporTestData.customerReference)
    await exportPage.enteringTestDescription(exporTestData.testDescription)
    await exportPage.choosingOriginCountry(exporTestData.originCountry)
    await exportPage.clickingTransitInsurance(exporTestData.transitInsurance)
    await exportPage.clickingATL(exporTestData.authorityToLeave,exporTestData.aTLDescription)
    await exportPage.clickingDangerousGoods(exporTestData.dangerousGoods,exporTestData.uNNNumber,exporTestData.dgPackageType,exporTestData.dgPackageGroup,exporTestData.technicalName,exporTestData.classDivision)
    await exportPage.clickingHandUnload(exporTestData.handUnload)
    await exportPage.clickingMineSite(exporTestData.mineSite)
    await exportPage.clickingTimeSlot(exporTestData.timeSlot,exporTestData.timeSlotDeliveryDate,exporTestData.timeSlotDeliveryTime)
    await exportPage.clickingExhibitionDelivery(exporTestData.exhibitionDelivery)
    await exportPage.clickingTailGate(exporTestData.collectionTailGate,exporTestData.deliveryTailGate)
    await exportPage.clickingfedEXSignature(exporTestData.fedEXISR,exporTestData.fedEXDSR,exporTestData.fedEXASR)
    await exportPage.enteringWeight(exporTestData.weight)
    await exportPage.enteringLength(exporTestData.length)
    await exportPage.enteringWidth(exporTestData.width)
    await exportPage.enteringHeight(exporTestData.height)
    await exportPage.choosingCurrencyType(exporTestData.currency)
    await exportPage.enteringCustomValue(exporTestData.customValue)
    await exportPage.chooseMultipleItems(exporTestData.count)
    await exportPage.clickingQuoteButton()
    await exportPage.exportPageSpinner()
    await exportPage.gettingRatesOrErrorMessage()
    await exportPage.clickingOKButton()
    await exportPage.clickingNextButton()
    await exportPage.exportPageSpinner()
    await commercialInvoice.readingQuoteAndPriceDetails()
    await commercialInvoice.choosingCommercialInvoiceExportPage(exporTestData.invoiceType,exporTestData.paperOrDigital,exporTestData.eORI,exporTestData.tAXID,exporTestData.iTNNumber,exporTestData.invoiceNo,exporTestData.goodsDescription,exporTestData.invoiceWeight,exporTestData.sourceCountry,exporTestData.commodityCode,exporTestData.quantity,exporTestData.unitPrice)
    await collectionPage.readingQuoteAndPriceDetails()
    await collectionPage.clickingDropAtDepot()
    await collectionPage.clickingShipButtonExportPage()
    await collectionPage.collectionPageSpinner()
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.gettingSuccessMessage()
    const trackingNumber = await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel([exporTestData.labelUrl,trackingNumber])
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.clickingViewReceipt(exporTestData.receiptUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintCommercialInvoice(exporTestData.commercialInvoiceUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintManifest(exporTestData.manifestUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingTrackingHistory()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await trackingHistory.filteringConsingment(exporTestData.filterBy,trackingNumber)
    await trackingHistory.clickingRow(trackingNumber)
    await trackingHistory.trackingHistoryPageSpinner()
    await trackingHistory.clickingTrackingAndPOD()
    await trackingHistory.clickShippingDocument([exporTestData.labelUrl,trackingNumber],exporTestData.receiptUrl,exporTestData.manifestUrl,exporTestData.mailTo,exporTestData.starTrackManifest,exporTestData.filterBy,exporTestData.commercialInvoiceUrl,exporTestData.commercialInvoiceLogoUrl)
    await page.waitForTimeout(4000)
    await trackingHistory.clickingVoidButton()
    await page.waitForTimeout(3000) 
})}