import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ExportDomesticPage } from "../Pages/ExportDomesticPage";
import { CollectionOptionPage } from "../Pages/CollectionOptionPage";
import { LabelsAndDocumentsPage } from "../Pages/LabelsAndDocumentsPage";
import { TrackingHistoryPage } from "../Pages/TrackingHistoryPage";
//import exportData  from "../Test-data/exportDomesticTestData.json";
//import exportData from "../Test-data/exportPagePremiumTestData.json";
//import exportData from "../Test-data/exportPageRoadExpressTestData.json"
//import exportData from "../Test-data/roadExpressTestData.json"
import exportData from "../Test-data/exportPageMaximumAllowedWOA.json";

for(const exportPage of exportData){
test.setTimeout(1200000)
test(`The testcase ID ${exportPage.testTitle}`,async ({page,context}) => {
    const login = new LoginPage(page,context)
    const exportDomestic = new ExportDomesticPage(page,context)
    const collectionOption = new CollectionOptionPage(page,context)

    await login.loadingURL()
    await exportDomestic.clickingExportPage()
    await exportDomestic.exportPageSpinner()
    await page.waitForTimeout(6000)
    await exportDomestic.enteringCollectionCompanyName(exportPage.collectionCompany)
    await exportDomestic.enteringCollectionContactName(exportPage.collectionConctact)
    await exportDomestic.enteringCollectionAddress1(exportPage.collectionAddress1)
    await exportDomestic.enteringCollectionCountry(exportPage.collectionCountry)
    await exportDomestic.clickingCollectionState(exportPage.collectionState,exportPage.collectionCountry)
    await exportDomestic.enteringCollectionCity(exportPage.collectionCity)
    await exportDomestic.enteringCollectionPostcode(exportPage.collectionPostcode)
    await exportDomestic.enteringCollectionDial(exportPage.collectionDial)
    await exportDomestic.enteringCollectionPhone(exportPage.collectionPhone)
    await exportDomestic.enteringCollectionEmailID(exportPage.collectionEmail)
    await exportDomestic.enteringDeliveryCompanyName(exportPage.deliveryCompany)
    await exportDomestic.enteringDeliveryContactName(exportPage.deliveryContact)
    await exportDomestic.enteringDeliveryAddress1(exportPage.deliveryAddress1)
    await exportDomestic.clickingDeliveryCountry(exportPage.deliveryCountry)
    await exportDomestic.clickingDeliveryState(exportPage.deliveryState,exportPage.deliveryCountry)
    await exportDomestic.enteringDeliveryCity(exportPage.deliveryCity)
    await exportDomestic.enteringDeliveryPostcode(exportPage.deliveryPostcode)
    await exportDomestic.enteringDeliveryDial(exportPage.deliveryDial)
    await exportDomestic.enteringDeliveryPhone(exportPage.deliveryPhone)
    await exportDomestic.enteringDeliveryEmailID(exportPage.deliveryEmail)
    await exportDomestic.clickingResidential(exportPage.residentialCollection,exportPage.residentialDelivery)
    await exportDomestic.clickingPOBoxDelivery(exportPage.poBoxDelivery)
    await exportDomestic.clickingServiceCompany(exportPage.serviceCompany)
    await exportDomestic.clickingServiceType(exportPage.serviceType)
    await exportDomestic.clickingPackageType(exportPage.packageType)
    await exportDomestic.enteringCustomerRef(exportPage.customerReference)
    await exportDomestic.enteringTestDescription(exportPage.testDescription)
    await exportDomestic.clickingTransitInsurance(exportPage.transitInsurance)
    await exportDomestic.clickingATL(exportPage.authorityToLeave,exportPage.aTLDescription)
    await exportDomestic.clickingDangerousGoods(exportPage.dangerousGoods,exportPage.uNNNumber,exportPage.dgPackageType,exportPage.dgPackageGroup,exportPage.technicalName,exportPage.classDivision)
    await exportDomestic.clickingHandUnload(exportPage.handUnload)
    await exportDomestic.clickingMineSite(exportPage.mineSite)
    await exportDomestic.clickingTimeSlot(exportPage.timeSlot,exportPage.timeSlotDeliveryDate,exportPage.timeSlotDeliveryTime)
    await exportDomestic.clickingExhibitionDelivery(exportPage.exhibitionDelivery)
    await exportDomestic.clickingTailGate(exportPage.collectionTailGate,exportPage.deliveryTailGate)
    await exportDomestic.clickingfedEXSignature(exportPage.fedEXISR,exportPage.fedEXDSR,exportPage.fedEXASR)
    await exportDomestic.enteringWeight(exportPage.weight)
    await exportDomestic.enteringLength(exportPage.length)
    await exportDomestic.enteringWidth(exportPage.width)
    await exportDomestic.enteringHeight(exportPage.height)
    await exportDomestic.chooseMultipleItems(exportPage.count)
    await exportDomestic.clickingQuoteButton()
    await exportDomestic.exportPageSpinner()
    //await exportDomestic.gettingRatesOrErrorMessage()
    //await exportDomestic.validatingMHFeeST(exportPage.manualHandlingCharge)
    await exportDomestic.validatingOversizeFeeST(exportPage.oversizeCharges,exportPage.manualHandlingCharge)
    await exportDomestic.clickingOKButton()
    /*await exportDomestic.clickingNextButton()
    await exportDomestic.exportPageSpinner()
    await collectionOption.clickingDropAtDepot()
    //await collectionOption.clickingScheduleACollection(exportPage.date,exportPage.parcelReadyFrom,exportPage.latestPickupTime,exportPage.pickupLocation,exportPage.locationDescription)
    await collectionOption.clickingShipButtonExportPage()
    await collectionOption.collectionPageSpinner()
    await page.waitForTimeout(3000)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    await lablesAndShippingDocs.gettingSuccessMessage()
    const trackingNumber = await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel([exportPage.labelUrl,trackingNumber])
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.clickingViewReceipt(exportPage.receiptUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintManifest(exportPage.manifestUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingTrackingHistory()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    const trackingHistory = new TrackingHistoryPage(page,context)
    await trackingHistory.filteringConsingment(exportPage.filterBy,trackingNumber)
    await trackingHistory.clickingRow(trackingNumber)
    await trackingHistory.trackingHistoryPageSpinner()
    await trackingHistory.clickingTrackingAndPOD()
    await trackingHistory.clickShippingDocument([exportPage.labelUrl,trackingNumber],exportPage.receiptUrl,exportPage.manifestUrl,exportPage.mailTo,exportPage.starTrackManifest,exportPage.filterBy,exportPage.commercialInvoiceUrl,exportPage.commercialInvoiceLogoUrl)
    await page.waitForTimeout(4000)
    await trackingHistory.clickingVoidButton()
    await page.waitForTimeout(3000)*/

})}