import { test } from "@playwright/test";
import { LoginPage } from "../Pages/LoginPage";
import { ImportPage } from "../Pages/ImportPage";
import { CollectionOptionPage } from "../Pages/CollectionOptionPage";
import { LabelsAndDocumentsPage } from "../Pages/LabelsAndDocumentsPage";
import { TrackingHistoryPage } from "../Pages/TrackingHistoryPage";
import { CommercialInvoicePage } from "../Pages/CommercialInvoicePage";
import importTest from "../Test-data/importInternationalTestData.json";
//import importTest from "../Test-data/importVanuatu.json"

for(const importTestData of importTest){
test.setTimeout(1200000)
test(`The test title ${importTestData.testTitle}`, async ({page,context}) => {
    const login = new LoginPage(page,context)
    const importPage = new ImportPage(page,context)
    const collectionPage = new CollectionOptionPage(page,context)
    const lablesAndShippingDocs = new LabelsAndDocumentsPage(page,context)
    const trackingHistory = new TrackingHistoryPage(page,context)
    const commercialInvoice = new CommercialInvoicePage(page,context)

    await login.loadingURL()
    await importPage.clickingImportPage()
    await importPage.importPageSpinner()
    await page.waitForTimeout(6000)
    await importPage.enteringCollectionCompanyName(importTestData.collectionCompany)
    await importPage.enteringCollectionContactName(importTestData.collectionConctact)
    await importPage.enteringCollectionAddress1(importTestData.collectionAddress1)
    await importPage.enteringCollectionCountry(importTestData.collectionCountry)
    await importPage.clickingCollectionState(importTestData.collectionState, importTestData.collectionCountry)
    await importPage.enteringCollectionCity(importTestData.collectionCity)
    await importPage.enteringCollectionPostcode(importTestData.collectionPostcode)
    await importPage.enteringCollectionDial(importTestData.collectionDial)
    await importPage.enteringCollectionPhone(importTestData.collectionPhone)
    await importPage.enteringCollectionEmailID(importTestData.collectionEmail)
    await importPage.enteringDeliveryCompanyName(importTestData.deliveryCompany)
    await importPage.enteringDeliveryContactName(importTestData.deliveryContact)
    await importPage.enteringDeliveryAddress1(importTestData.deliveryAddress1)
    await importPage.clickingDeliveryCountry(importTestData.deliveryCountry)
    await importPage.clickingDeliveryState(importTestData.deliveryState, importTestData.deliveryCountry)
    await importPage.enteringDeliveryCity(importTestData.deliveryCity)
    await importPage.enteringDeliveryPostcode(importTestData.deliveryPostcode)
    await importPage.enteringDeliveryDial(importTestData.deliveryDial)
    await importPage.enteringDeliveryPhone(importTestData.deliveryPhone)
    await importPage.enteringDeliveryEmailID(importTestData.deliveryEmail)
    await importPage.clickingServiceCompany(importTestData.serviceCompany)
    await importPage.clickingServiceType(importTestData.serviceType)
    await importPage.clickingLabelDeliveryMethod(importTestData.labelDeliveryMethod)
    await importPage.clickingPackageType(importTestData.packageType)
    await importPage.enteringCustomerRef(importTestData.customerRef)
    await importPage.enteringTestDescription(importTestData.description)
    await importPage.choosingOriginCountry(importTestData.originCountry)
    await importPage.clickingTransitInsurance(importTestData.transitInsurance)
    await importPage.clickingDangerousGoods(importTestData.dangerousGoods,importTestData.uNNNumber,importTestData.dgPackageType,importTestData.dgPackageGroup,importTestData.technicalName,importTestData.classDivision)
    await importPage.clickingfedEXSignature(importTestData.fedEXISR,importTestData.fedEXDSR,importTestData.fedEXASR)
    await importPage.enteringWeight(importTestData.weight)
    await importPage.enteringLength(importTestData.length)
    await importPage.enteringWidth(importTestData.width)
    await importPage.enteringHeight(importTestData.height)
    await importPage.choosingCurrencyType(importTestData.currency)
    await importPage.enteringCustomValue(importTestData.customValue)
    await importPage.chooseMultipleItems(importTestData.count)
    await importPage.clickingQuoteButton()
    await importPage.importPageSpinner()
    await importPage.gettingRatesOrErrorMessage()
    await importPage.clickingOKButton()
    await importPage.clickingNextButton()
    await importPage.importPageSpinner()
    await commercialInvoice.readingQuoteAndPriceDetails()
    await commercialInvoice.choosingCommercialInvoiceImportPage(importTestData.invoiceType,importTestData.paperOrDigital,importTestData.eORI,importTestData.tAXID,importTestData.iTNNumber,importTestData.invoiceNo,importTestData.goodsDescription,importTestData.invoiceWeight,importTestData.sourceCountry,importTestData.commodityCode,importTestData.quantity,importTestData.unitPrice)
    await collectionPage.readingQuoteAndPriceDetails()
    await collectionPage.clickingDropAtDepot()
    await collectionPage.clickingShipButtonImportPage()
    await collectionPage.collectionPageSpinner()
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.gettingSuccessMessage()
    const trackingNumber = await lablesAndShippingDocs.gettingTrackingNo()
    await lablesAndShippingDocs.gettingFromAddress()
    await lablesAndShippingDocs.gettingToAddress()
    await lablesAndShippingDocs.clickingViewAndPrintlabel([importTestData.labelUrl,trackingNumber])
    await page.waitForTimeout(3000)
    await lablesAndShippingDocs.clickingViewReceipt(importTestData.receiptUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintCommercialInvoice(importTestData.commercialInvoiceUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingViewAndPrintManifest(importTestData.manifestUrl)
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await lablesAndShippingDocs.clickingTrackingHistory()
    await lablesAndShippingDocs.labelsAndDocumentsPageSpinner()
    await trackingHistory.filteringConsingment(importTestData.filterBy,trackingNumber)
    await trackingHistory.clickingRow(trackingNumber)
    await trackingHistory.trackingHistoryPageSpinner()
    await trackingHistory.clickingTrackingAndPOD()
    await trackingHistory.clickShippingDocument([importTestData.labelUrl,trackingNumber],importTestData.receiptUrl,importTestData.manifestUrl,importTestData.mailTo,importTestData.starTrackManifest,importTestData.filterBy,importTestData.commercialInvoiceUrl,importTestData.commercialInvoiceLogoUrl)
    await page.waitForTimeout(4000)
    await trackingHistory.clickingVoidButton()
    await page.waitForTimeout(3000)
    
})}